### ISSUE TITLE
Domain / DNS

### ISSUE THREAD

**Issue by bienflorencia** [gbif/hp-biodiversidata#1]
The domain is [biodiversidata.org](https://biodiversidata.org).

**Comment by MattBlissett** [comment]
Thanks, it's now ready for you to 

1. make a release using https://github.com/gbif/hp-biodiversidata/releases
2. change the DNS with [these instructions](https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md) ("Apex domain" part).

**Comment by bienflorencia** [comment]
Matt, it's done. Hope it will update soon, will close it when it's live. Thanks!
