### ISSUE TITLE
4.9 mb header image

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-biodiversidata#2]
The header image on the home page is taken directly from a inaturalist url. It is 4.9mb and therefore takes forever to show. Also your image will disappear if inat change their urls. 

I suggest that you make a local copy in your repo and use that instead. That will ensure that the image will always be there, and it means that it will go through our image service that scales and compress the image to be more suitable for web usage.

https://github.com/gbif/hp-biodiversidata/blob/master/home.md

**Comment by MortenHofft** [comment]
The same goes for other images on the site I notice.

**Comment by bienflorencia** [comment]
Thanks, Morten! I had this among my tasks. Will do it asap.

**Comment by bienflorencia** [comment]
I made a local copy on the repo of the images used in all pages of 'acerca-de' and 'recursos'.
