### ISSUE TITLE
counts on records are displayed as html

### ISSUE THREAD

**Issue by bienflorencia** [gbif/hp-biodiversidata#3]
Hi @MortenHofft, can you help me out with this:

<img width="1146" alt="image" src="https://github.com/gbif/hp-biodiversidata/assets/25744687/a1d4a756-ad77-407a-91bf-493455a2c3d5">

After my last update, this is how numbers are displayed.
Cheers!

**Comment by timrobertson100** [comment]
Hi @bienflorencia 

I fixed it with [this commit](https://github.com/gbif/hp-biodiversidata/commit/e1fec07b761b81eb7f3a406c79756e61298fb1e3) in [your staging site](https://biodiversidata.hp.gbif-staging.org/). You were just missing a closing `>` on your `<span...` 

Please make a release when you are ready to push that to production.

Thanks

**Comment by bienflorencia** [comment]
Many thanks, Tim! Weirdly, it was working before.
I'll make a new release.

Cheers!
