### ISSUE TITLE
recent change not showing on the staging

### ISSUE THREAD

**Issue by bienflorencia** [gbif/hp-biodiversidata#4]
Hi  @timrobertson100 and @MortenHofft ,
Is there any reason why my recent changes are not being processed? I don't see them on the builds nor on staging.

Thanks!

**Comment by MattBlissett** [comment]
Hi,

I don't know why nothing was happening. Github was not informing our system of changes, and wasn't giving any error messages either. I've deleted and recreated the connection, and I think it is now working.

**Comment by bienflorencia** [comment]
Wow, so fast. Thanks, Matt! It's working now.
